PASSWORD = "adminxyz"

OPENAI_API_KEY = "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"